### ISSUE TITLE
'Client' object has no attribute 'options'

### ISSUE THREAD

**Issue by RayZhao1998** [NUAA-Open-Source/NUAA-iCal-Python#6]
- ubuntu 16.04
- python 3.5
![image](https://user-images.githubusercontent.com/22616933/44628972-b787c500-a97b-11e8-96f0-057a2a588f3c.png)

**Comment by Triple-Z** [comment]
FIXED.

b21f1429bb8b498b0669a4995d8a

**Comment by Triple-Z** [comment]
@RayZhao1998 `0.5.5` 已更新。

https://pypi.org/project/NUAAiCal/0.5.5/
